services:
  back-end:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/greeting"]
      interval: 5s
      timeout: 5s
      retries: 5
